jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as it uses the current rustc version as its cache key
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: Cache ~/.cargo/bin
        uses: actions/cache@v3

        env:
          cache-name: cache-cargo
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install sccache
        run: if (Test-Path -Path ~\.cargo\bin\sccache.exe -PathType Leaf) {echo "Sccache is already installed"} else { cargo install sccache }

      - name: Install fleet
        run: if (Test-Path -Path ~\.cargo\bin\fleet.exe -PathType Leaf) {echo "Fleet is already installed"} else { cargo install fleet-rs }

      - name: Run app using fleet
        run: fleet run --bin fleet
